AWSTemplateFormatVersion: 2010-09-09
Description: 'Create Import Glue job from S3 to Amazon Keyspaces'
Parameters:
  KeyspacesBucketName: 
      NoEcho: false
      Description: S3 bucket name to store artifacts
      Type: String
      Default: amazon-keyspaces-glue-accountnumber
      MinLength: 3
      MaxLength: 63
      AllowedPattern: (?!(^xn--|.+-s3alias$))^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$
  KeyspaceName: 
      NoEcho: false
      Description: Cassandra Keyspace name
      Type: String
      Default: mykeyspace
      MinLength: 3
      MaxLength: 48
  TableName: 
      NoEcho: false
      Description: Cassandra Table name
      Type: String
      Default: mytable
      MinLength: 3
      MaxLength: 48
Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties: 
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${KeyspacesBucketName}/scripts/import-sample.scala'
      DefaultArguments: 
        "--job-language": "scala"
        "--user-jars-first": "true"
        "--extra-jars": !Sub 's3://${KeyspacesBucketName}/jars/spark-cassandra-connector-assembly_2.12-3.1.0.jar, s3://${KeyspacesBucketName}/jars/aws-sigv4-auth-cassandra-java-driver-plugin-4.0.9-shaded.jar,s3://${KeyspacesBucketName}/jars/spark-extension_2.12-2.8.0-3.4.jar, s3://${KeyspacesBucketName}/jars/amazon-keyspaces-helpers-1.0-SNAPSHOT.jar'
        "--extra-files": !Sub 's3://${KeyspacesBucketName}/conf/keyspaces-application.conf'
        "--enable-metrics": "true"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-spark-ui": "true"
        "--spark-event-logs-path": !Sub "s3://${KeyspacesBucketName}/spark-logs/"
        "--write-shuffle-files-to-s3": "true"
        "--write-shuffle-spills-to-s3": "true"
        "--TempDir": !Sub 's3://${KeyspacesBucketName}/shuffle-space/import-sample/'
        "--FORMAT": "parquet"
        "--KEYSPACE_NAME": !Sub '${KeyspaceName}'
        "--TABLE_NAME": !Sub '${TableName}'
        "--S3_URI": !Sub 's3://${KeyspacesBucketName}/export-shuffled/'
        "--DRIVER_CONF": "keyspaces-application.conf"
        #"--DISTINCT_KEYS": "id,create_date"
        "--class": "GlueApp"
      #Connections: 
      #  ConnectionsList
      Description: 'Import from s3'
      #ExecutionClass: String
      #ExecutionProperty: 
        #ExecutionProperty
      GlueVersion: "3.0"
      #LogUri: String
      #MaxCapacity: Double
      #MaxRetries: Double
      Name: 'Amazon Keyspaces Import from s3'
      #NonOverridableArguments: Json
      #NotificationProperty: 
      #  NotificationProperty
      NumberOfWorkers: 2
      Role: !ImportValue: 'KeyspacesBucketNameExport'
      #SecurityConfiguration: String
      #Tags: Json
      #Timeout: Integer
      WorkerType: G.1X
